# (PART) Understanding `parse_for_major_flags()` Output {-}

# Function Parameters

The `parse_for_major_flags()` function is a powerful tool designed to analyze the results of the `autovalid()` function and identify interviews that fail major tests. These major tests include considerations for interview duration, missing data, percent match, location discrepancies, and straightlining.

This chapter describes the different parameters in the function that can be adjusted for your specific analysis. 

The major tests in the `parse_for_major_flags()` are:

- **`timer_fail_count`**
- **`thresh_max_miss`**
- **`thresh_max_pct`**
- **`do_timer`**
- **`do_variance`**
- **`do_percent_match`**
- **`do_missingness`**
- **`do_location`**

## `timer_fail_count`

`timer_fail_count` uses the 4 timers in the `autovalid()` function to flag time duration issues. The default input is 3 and can go up to 4 timers. 

## `thresh_max_miss`

`thresh_max_miss` is the threshold for the maximum acceptable missingness percentage in an interview. The default is 0.15. 

## `thresh_max_pct`

`thresh_max_miss` determines the threshold for maximum acceptable percent match across interviews. The default is 0.85.

## `do_timer`

The `do_timer` parameter flags interviews that are too short and is set TRUE by default. Set `do_timer` to FALSE to exclude timer checks from the analysis.

## `do_variance`

The `do_variance` parameter flags straightlining and is set TRUE by default. Set `do_variance` to FALSE to exclude straightlining checks from the analysis.

## `do_percent_match`

The `do_percent_match` parameter flags high percent match and is set TRUE by default. Set `do_percent_match` to FALSE to exclude percent match checks from the analysis. 

## `do_missingness` 

The `do_missingness` parameter flags high levels of missing responses in an interivew and is set to TRUE by default. Set `do_missingness` to FALSE to exclude missingness checks from your analysis.

## `do_location`

The `do_location` parameter flags questionable locations and is set to TRUE by default. Set `do_location` to FALSE to exclude location checks from the analysis. 

# Output Overview

This chapter describes the output of the `parse_for_major_flags()` function. The output of `parse_for_major_flags()` include data frame with information about interviews that fail one or more of the major tests, validation checks, and identifies interviews to refield. 

The output looks like this list:

- **`refield_report`** (data frame)
- **`refield_validation_results`** (data frame)
- **`refield_interviews`** (data frame)

## `refield_report`

`refield_report` is a data frame that provides information about interviews that failed one or more major tests. It includes reasons for failure, such as being too short, having high missingness, etc.


## `refield_validation_results`

`refield_validation_results` provides a summary of the major validation checks for each flagged interview. It includes the total number of flags as well as information about timers, missingness, percent match, location checks, and variance checks. 

This table gives a concise view of the validation results for flagged interviews.

## `refield_interviews`
`refield_interviews` includes a subset of the original interview data but only for the interviews that failed one or more major tests. It allows for a detailed examination of the responses and characteristics of the flagged interviews.