# (PART) Understanding `prep_data()` Output {-}

# Output Overview

This chapter describes the output of the `prep_data()` function. The output of `prep_data()` creates a table that is ready to use for the automatic validation.

The overall output of `prep_data()` is a list of five objects called **`pre_data`**, **`csv_data`**, **`aud_data`**, **`duplicated_interviews`**, and **`nonvalid`**.

The output looks like this list:

- **`pre_data`** (data frame)
- **`csv_data`** (data frame)
- **`aud_data`** (data frame)
- **`duplicated_interviews`** (data frame)
- **`nonvalid`** (list)

The next sections look at each of the objects `prep_data()` returns.

## `pre_data`

The `pre_data` data frame is the preprocessed data to undergo automatic validation. `pre_data` contains the organized and cleaned data after handling duplicates, collapsing randomized columns, and adding audit information.

## `csv_data`

The `csv_data` data frame formats the data to make it easier to export as a CSV file. 

## `aud_data`

The `aud_data` data frame processeses the audit file to review timers and enumerator behaviors. 

## `duplicated_interviews`

The `duplicated_interviews` data frame contains information about duplicated interviews, specifically the duplicated UUIDs. The output can be a character string indicating the absence of duplicated UUIDs.

## `nonvalid`

The `nonvalid` list contains different types of non-valid interviews. Each element of the list corresponds to a specific category of non-valid interviews.

Categories of non-valid interviews: 

- `Unsuccessful_Knock`
- `Failed_Kish`
- `No_Consent`
- `Incomplete`

