# (PART) Validation Test Categories {-}

# Timer Checks {#timer-checks}

The `autovalid()` function performs ten checks related to time and gives an overall score. The results are in the columns:

- **`CHECK_TIMER1_AFTER_9AM`**
- **`CHECK_TIMER1_BEFORE_8PM`**
- **`CHECK_TIMER1_ABOVE_MIN`**
- **`CHECK_TIMER1_BELOW_MAX`**
- **`CHECK_TIMER2_ABOVE_MIN`**
- **`CHECK_TIMER2_BELOW_MAX`**
- **`CHECK_TIMER3_ABOVE_MIN`**
- **`CHECK_TIMER3_BELOW_MAX`**
- **`CHECK_TIMER4_ABOVE_MIN`**
- **`CHECK_TIMER4_BELOW_MAX`**
- **`SCORE_TIMER`**

## Understanding the Four Timers

`autovalid()` uses four different measures of time to calculate the length of a survey. These timers are called `TIMER1`, `TIMER2`, `TIMER3`, and `TIMER4`.

### `TIMER1`

`TIMER1` is calculated from the `start` and `end` time recorded in the survey.
These times are found in the raw data.

The other three timers are all calculated from the audit files.

### `TIMER2`

`TIMER2` is calculated using the last recorded `start` and first recorded `start` in the associated interview's audit file. 

All elements in an audit file have a `start` value, but not all have an `end` value, so that is why only values from the `start` column are used.

### `TIMER3`

`TIMER3` is calculated using the sum of the time spent on each page of the survey, according to the audit file.

Once the survey and audit file timers start, they do not stop. If an interviewer leaves a survey and returns to it the duration of the survey may appear longer than it actually was. This timer does not include such pauses.

### `TIMER4`

`TIMER4` is calculated using the sum of the time spent on each page of the survey for questions that are between the first and last substantive question.

By default, the first substantive question is set to `"Q2061A"` and the last substantive question is determined as the last question that begins with `"Q"`.

## Time of Day

`autovalid()` uses the time recorded in the survey to determine whether the interview took place after 9am and before 8pm.

## Min/Max Length

The variables called `CHECK_TIMERX_ABOVE_MIN` and `CHECK_TIMERX_BELOW_MAX`, where `X` is 1 through 4, are all logicals telling the user whether the timer in question recorded a time above the minimum time and below the maximum time, respectively. By default, the minimum time is set to 30 minutes and the maximum time is set to 75 minutes.

## `SCORE_TIMER`

The `SCORE_TIMER` variable calculates the mean of all the check variables.

## Changing Defaults

There are **four** arguments in `autovalid()` that can be used to change the defaults for the timer checks. They are:

- `thresh_opening`: The earliest time of day an interview should begin.
  - Use a 24 hour clock time.
  - Default is `9`.
  - Associated with `CHECK_TIMER1_AFTER_9AM`.
  - NOTE: Even if you change the default, the variable name will **not** change. It will still say `CHECK_TIMER1_AFTER_9AM`.
- `thresh_closing`: The latest time of day an interview should begin.
  - Use a 24 hour clock time.
  - Default is `20`.
  - Associated with `CHECK_TIMER1_BEFORE_8PM`.
  - NOTE: Even if you change the default, the variable name will **not** change. It will still say `CHECK_TIMER1_BEFORE_8PM`.
- `thresh_min_len`: The minimum amount of time in minutes an interview should take.
  - Use a positive integer.
  - Default is `30`.
  - Associated with `CHECK_TIMERX_ABOVE_MIN`, where `X` is 1 through 4.
- `thresh_max_len`: The maximum amount of time in minutes an interview should take.
  - Use a positive integer.
  - Default is `75`.
  - Associated with `CHECK_TIMERX_BELOW_MAX`, where `X` is 1 through 4.


The following is an example of changing the defaults in `autovalid()` for the timer checks. The object `prepped_data` is the output of the `prep_data()` function. See [Chapter 2](#basic-use) for a refresher.

```{r timer-check-1,eval=FALSE}

autovalid(prepped_data,
          thresh_opening = 8, # Does the interview take place after 8am?
          thresh_closing = 16, # Does the interview take place before 4pm?
          thresh_min_len = 20, # Does the interview take longer than 20 minutes?
          thresh_max_len = 120 # Does the interview take less than 2 hours?
          )

```

## Result Columns

There are an additional six column that are related to the timer checks that can be thought of as the "result columns". They are `TIMER1`, `TIMER2`, `TIMER3`, `TIMER4`, `COUNT_ABOVE_MIN` and `COUNT_BELOW_MAX`.

The first four simply record the time of the interview determined by each timer described in the sections above.

The variables `COUNT_ABOVE_MIN` and `COUNT_BELOW_MAX` record the number of timers that pass the minimum and maximum length requirements, respectively.
